FROM python:3.9-slim-buster

WORKDIR /home/app

COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .
ENTRYPOINT ["celery", "-A", "acelery.tasks worker"]